# Base Configuration - Common settings for all environments
spring:
  application:
    name: Kraft
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Ho_Chi_Minh

# Server Configuration - Common settings
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Logging Configuration - Common settings
logging:
  charset:
    console: UTF-8
    file: UTF-8

# Environment-specific configurations are in:
# - application-dev.yml (for development)
# - application-prod.yml (for production)