spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/kraftdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:your-super-secret-jwt-key-for-production}
      expiration: 7200000 # 2 hours

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:9002}

logging:
  level:
    com.mss301.kraft: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# App configuration
app:
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}
    base-url: ${FILE_BASE_URL:http://localhost:8080/api/files}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:9002}

